let a=15;
let b='16';
console.log(a==b);
console.log(a===b);
console.log(a=b);
let age =20;
console.log(age>20);
console.log(age<20);
console.log(age>=20);
console.log(age<=20);
console.log(age===20);
console.log(age!==20);
console.log(age=='20');
console.log(age==='20');